sudo: false
language: haskell
addons:
  apt:
    packages:
    - libev-dev
before_install:
- git clone https://github.com/galoisinc/ivory
- export IVORY_REPO=$PWD/ivory
- git clone https://github.com/galoisinc/tower
- export TOWER_REPO=$PWD/tower
install:
- cabal install alex happy
script:
- make create-sandbox test
ghc:
- 7.8
