language: haskell
before_install:
  - git clone https://github.com/galoisinc/ivory
  - git clone https://github.com/galoisinc/tower
  - export IVORY_REPO=$PWD/ivory
  - export TOWER_REPO=$PWD/tower
install:
  - cabal install alex
  - cabal install happy
script:
  - IVORY_REPO=$IVORY_REPO TOWER_REPO=$TOWER_REPO make create-sandbox
  - make build
  - make test
ghc:
  - 7.6.3
  - 7.8.3
env:
  - ENV_TEST_TARGET=tower
  - ENV_TEST_TARGET=tower-statemachine
  - ENV_TEST_TARGET=tower-config
  - ENV_TEST_TARGET=tower-aadl
